version: '3.8'

services:
  nginx:
    image: local-nginx
    ports:
      - "80:80"  # Changed "eighty:80" to "80:80" for proper port mapping
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Removed extra 'i' from nginx.confi
    networks:
      - nginx-network

  python-app:
    image: local-python-app
    container_name: python_app
    expose:
      - "8000"  # Changed "eight thousand" to "8000" to match the Python app port
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge  # Fixed typo "bridg" to "bridge"
    # options:
    #   compelex_option: value  # Fixed typo "compelex_option" to "complex_option"
